### ISSUE TITLE
Cannot import modules in development mode on local machine

### ISSUE THREAD

**Issue by Fidget-Spinner** [source-academy/frontend#2373]
Reproducer:
```
yarn run start
```
then
```
import {make_point} from "curve";
```
Traceback in console
```
index.js:1 SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at getModuleManifest (moduleLoader.ts:49:1)
    at memoized (lodash.js:10620:1)
    at loadModuleTabs (moduleLoader.ts:97:1)
    at appendModulesToContext (utils.ts:100:1)
    at fullJSRunner.ts:60:1
    at Generator.next (<anonymous>)
    at errors.ts:96:1
    at new Promise (<anonymous>)
    at push../node_modules/js-slang/dist/runner/fullJSRunner.js.__awaiter (errors.ts:96:1)
    at fullJSRunner (fullJSRunner.ts:46:1)
    at index.ts:357:1
    at Generator.next (<anonymous>)
    at loopVerifier.ts:131:1
    at new Promise (<anonymous>)
    at push../node_modules/js-slang/dist/index.js.__awaiter (loopVerifier.ts:131:1)
    at runFilesInContext (index.ts:316:1)
    at index.ts:309:1
    at Generator.next (<anonymous>)
    at loopVerifier.ts:131:1
    at new Promise (<anonymous>)
    at push../node_modules/js-slang/dist/index.js.__awaiter (loopVerifier.ts:131:1)
    at runInContext (index.ts:304:1)
    at runCallEffect (redux-saga-core.esm.js:524:1)
    at runEffect (redux-saga-core.esm.js:1204:1)
    at digestEffect (redux-saga-core.esm.js:1271:1)
    at redux-saga-core.esm.js:721:1
    at Array.forEach (<anonymous>)
    at runRaceEffect (redux-saga-core.esm.js:716:1)
    at runEffect (redux-saga-core.esm.js:1204:1)
    at digestEffect (redux-saga-core.esm.js:1271:1)
    at next (redux-saga-core.esm.js:1161:1)
    at currCb (redux-saga-core.esm.js:1251:1)
    at runSelectEffect (redux-saga-core.esm.js:731:1)
    at runEffect (redux-saga-core.esm.js:1204:1)
    at digestEffect (redux-saga-core.esm.js:1271:1)
    at next (redux-saga-core.esm.js:1161:1)
    at currCb (redux-saga-core.esm.js:1251:1)
    at runSelectEffect (redux-saga-core.esm.js:731:1)
    at runEffect (redux-saga-core.esm.js:1204:1)
    at digestEffect (redux-saga-core.esm.js:1271:1)
    at next (redux-saga-core.esm.js:1161:1)
    at proc (redux-saga-core.esm.js:1108:1)
    at runCallEffect (redux-saga-core.esm.js:533:1)
    at runEffect (redux-saga-core.esm.js:1204:1)
    at digestEffect (redux-saga-core.esm.js:1271:1)
    at next (redux-saga-core.esm.js:1161:1)
    at currCb (redux-saga-core.esm.js:1251:1)
    at runSelectEffect (redux-saga-core.esm.js:731:1)
    at runEffect (redux-saga-core.esm.js:1204:1)
```

**Comment by Fidget-Spinner** [comment]
Nevermind, I'm mistaken. It seems that we need to serve the modules locally for local development. I will update the README instructions to indicate that.

**Comment by RichDom2185** [comment]
Closing this issue as it needs to action. Feel free to reopen if you encounter problems going ahead!
